confidential-containers/operator

- .github/ISSUE_TEMPLATE/bug_report.md
> Update issue templates, add bug report template

- README.md
> Update README and provide instructions to change payload

- controllers/ccruntime_controller.go
- controllers/common.go
> Implement CR Delete support

- controllers/ccruntime_controller.go
Add separate runtimeclass for confidential containers
> Add kata-cc runtimeClass

- bundle/manifests/confidentialcontainers.org_ccruntimes.yaml
- config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
- deploy/deploy.yaml
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>
> Add the short name "ccr" for CcRuntime

- README.md
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>
> Fix link to demo instructions in main README

- docs/INSTALL.md
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>
> Update install instructions to align with latest changes

- docs/PAYLOAD_IMAGE.md
Fixes: #60
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>
> Add basic documentation about the runtime payload image requirements

- tests/e2e/run-local.sh
- tests/e2e/tests_runner.sh
Added the -r RUNTIMECLASS option to both run-local.sh and
tests_runner.sh so that CI jobs will be able to specify the RUNTIMECLASS
to be used on tests.
For example, the following to run with kata-clh and kata-qemu-tdx
respectively:
$ ./run-local.sh -r kata-clh
$ ./run-local.sh -r kata-qemu-tdx
> ci: allow to run tests for different runtimeclasses

- config/samples/ccruntime.yaml
- tests/e2e/tests_runner.sh
Update bundle to the version that removed skopeo to test if
everything still works without it
> bundle: Update bundle to latest version

- config/samples/ccruntime-ssh-demo.yaml
Add a new payload with the ssh-demo decryption keys and config baked in for demo-ing an encrypted image
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
> Add ssh-demo sample payload

- config/samples/ccruntime-enclave-cc.yaml
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
> samples: add CcRuntime for enclave-cc

- .github/workflows/docker-publish.yml
- .github/workflows/makefile.yml
* checkout: v2 -> v3
* login-action: 28218f9b04b4f3f62068d7b6ce6ca5b26e35336c -> v2
* metadata-action:  98669ae865ea3cffbcbaa878cf57c20bbf1c6c38 -> v4
* build-push-action: ad44023a93711e3deb337508980b4b5e9bcdc5dc -> v3
* setup-go: v2 -> v3
> actions: Update GitHub Actions to their latest release

- .github/workflows/e2e.yaml
- .github/workflows/enclave-cc-cicd.yaml
Let's add the bare minimum CI / CD for Enclave CC, running a GitHub action once a day to make sure the latest published CI payload works as expected.
> actions: Add a proto CI/CD for Enclave CC

- config/samples/ccruntime/default/kustomization.yaml
- tests/e2e/tests_runner.sh
> ccruntime: Test with the latest kata payload

- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
> enclave-cc: Bump to v0.3.1 release

- tests/e2e/tests_runner.sh
Fixes: #158
Signed-Off-By: Ryan Savino <ryan.savino@amd.com>
> tests: export RUNTIMECLASS for all cases

- .github/workflows/docker-publish-latest-on-merge.yml
- .github/workflows/docker-publish-on-tag.yml
Add new workflow to build and push `main` and `latest` image on push to `main` branch
Fixes: #164
> workflow: Add build on push to main

- bundle/manifests/cc-operator.clusterserviceversion.yaml
- Add new kata-remote runtime class for peer pods configuration support
Fixes: #186
> remote: Add runtime class

- config/samples/ccruntime/base/ccruntime.yaml
Add host and mount path for cri-o
Fixes: #192
> install: Add cri-o paths

- config/release/kustomization.yaml
- config/samples/ccruntime/default/kustomization.yaml
- config/samples/ccruntime/peer-pods/kustomization.yaml
- config/samples/ccruntime/s390x/kustomization.yaml
- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
> payloads: Update kata-containers / enclave-cc payloads for the v0.5.0 release

- config/crd/kustomization.yaml
- config/default/kustomization.yaml
- config/samples/enclave-cc/hw/kustomization.yaml
Update deprecated fields
Add apiVersion and kind
Fixes: #209
> config: Update kustomize

- config/samples/ccruntime/default/kustomization.yaml
- config/samples/ccruntime/peer-pods/kustomization.yaml
- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
Update pre-install, kata-containers ans enclave-cc payloads to the latest ready for release testing
> Update components to test v0.6.0

- config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
- config/rbac/role.yaml
- controllers/ccruntime_controller.go
- main.go
> Add privileged label to the install namespace

- config/samples/ccruntime/s390x/kustomization.yaml
- tests/e2e/tests_runner.sh
This reverts commit bfba38f90a1cfe35de6053e6cebf1ec0d8ee2b1f. This will fix a test failure at http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04-s390x-SE-daily/
Fixes: #300
> config: Revert "config: Remove kata-qemu-se"

- config/release/kustomization.yaml
- config/samples/ccruntime/default/kustomization.yaml
- config/samples/ccruntime/peer-pods/kustomization.yaml
- config/samples/ccruntime/s390x/kustomization.yaml
- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/hw/kustomization.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
./hack/release-helper.sh update -o v0.12.0 -e v0.11.0 -k 3.13.0
> Release: Update payloads for v0.12.0

- api/v1beta1/ccruntime_types.go
- config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
ImagePullSecret is modified to imagePullSecret
> fix: the json tag of the ImagePullSecret prefix should be lowercase

- config/release/kustomization.yaml
- config/samples/ccruntime/default/kustomization.yaml
- config/samples/ccruntime/peer-pods/kustomization.yaml
- config/samples/ccruntime/s390x/kustomization.yaml
- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/hw/kustomization.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
PR for step#5 of [[Release] Check list for v0.13.0](https://github.com/confidential-containers/confidential-containers/issues/294)
> Release: Update payloads for v0.13.0

- .github/workflows/docker-publish-latest-on-merge.yaml
- .github/workflows/docker-publish-on-tag.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/lib-codeql.yaml
- .github/workflows/pre-install-image-publish-on-merge.yaml
- controllers/ccruntime_controller.go
- main.go
Updated github actions require us to address some new linter errors.
> go: Address new go linter errors

- config/release/kustomization.yaml
- config/samples/ccruntime/default/kustomization.yaml
- config/samples/ccruntime/peer-pods/kustomization.yaml
- config/samples/ccruntime/s390x/kustomization.yaml
- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/hw/kustomization.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
PR for step#5 of  [ Check list for v0.14.0](https://github.com/confidential-containers/confidential-containers/issues/304)
> Release: Update payloads for v0.14.0

- config/release/kustomization.yaml
- config/samples/ccruntime/default/kustomization.yaml
- config/samples/ccruntime/peer-pods/kustomization.yaml
- config/samples/ccruntime/s390x/kustomization.yaml
- config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
- config/samples/enclave-cc/hw/kustomization.yaml
- config/samples/enclave-cc/sim/kustomization.yaml
PR for step#5 of [check list for v0.15.0](https://github.com/confidential-containers/confidential-containers/issues/311) .
> Release: Update payloads for v0.15.0
