confidential-containers/operator

config/samples/_v1beta1_confidentialcontainersruntime.yaml

Instead of pointing to the latest released kata-deploy image, which does
not contain any work related to the confidential containers effort, let's
point to the `kata-deploy-cc:v0` one instead.
Signed-off-by: Fabiano Fidêncio <fabiano@fidencio.org>

samples: point to the correct kata-deploy image

---

controllers/ccruntime_controller.go

kata-deploy image uses the CONFIGURE_CC env variable to specifically add the CC config .

Add "CONFIGURE_CC=yes" env variable for kata-deploy image

---

Dockerfile

- Use docker.io/library/golang as container base image --
quay.io/bitnami/golang does not support e.g. s390x
- Do not specify GOARCH -- uses native anyway
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>
@bpradipt if you're very keen on keeping quay.io (e.g. because of rate limiting), we might be able to figure out something else

Do not assume amd64

---

Dockerfile

The bitnami images will only be available from dockerhub and gcr going
forward
Fixes: #34

Switch to dockerhub image for bitnami

---

.github/workflows/docker-publish.yml
.github/workflows/makefile.yml
LICENSE
README.md
controllers/ccruntime_controller.go
controllers/common.go
deploy/deploy.yaml
docs/INSTALL.md

The series is to ensure a workable setup when using`ccv0-demo` branch.
It merges key commits from `main` to `ccv0-demo` as well as points to correct images 
- Operator: quay.io/confidential-containers/operator:demo
- Payload: quay.io/confidential-containers/runtime-payload:v0
Tested the instructions successfully on a 2 node K8s cluster running on Ubuntu 20.04
```
kubectl get nodes -o wide
NAME               STATUS   ROLES                  AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
testk8s-master-0   Ready    control-plane,master   18h   v1.24.0   192.168.121.37   <none>        Ubuntu 20.04.3 LTS   5.4.0-91-generic   containerd://1.6.4
testk8s-worker-0   Ready    worker                 18h   v1.24.0   192.168.121.17   <none> …
```

Update ccv0 demo instructions

---

controllers/ccruntime_controller.go
controllers/common.go

This contains two patches. The first one adds code to delete pre-install and post-uninstall
done labels. The second one deletes the pre-install daemon set so that it will be started
again when a new CR is created. 
Fixes: #50 #54

allow re-installation by deleting labels and preinstall daemonset

---

api/v1beta1/ccruntime_types.go
api/v1beta1/zz_generated.deepcopy.go
bundle/manifests/confidentialcontainers.org_ccruntimes.yaml
config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
config/rbac/role.yaml
config/samples/ccruntime.yaml
controllers/ccruntime_controller.go
deploy/deploy.yaml

Currently, the RuntimeClassNames created by the operator is hard-coded to `kata`, `kata-clh` and `kata-qemu`.
This PR makes it possible for the CC runtime payload image authors to specify the desired RuntimeClassNames.
Consequently, this PR should make it easy to add support for enclave-cc , peer-pods etc without requiring changes to the operator code.
Fixes: #61 and #56

The PR adds support for specifying RuntimeClassNames in the CRD

---

controllers/ccruntime_controller.go

We need to update the CCRuntime CR after we have removed
the finalizer. When no postuninstall DaemonSet was used we
return values that mean we don't update the CR instance.
Fix this by updating the status before returning.
Fixes: #58 
Reported-by: Snir Sheriber <ssheribe@redhat.com>

Update ccruntime after finalizer removed

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime.yaml

Let's update the pre/post hooks image to point to the latest version of
the container-engine-for-cc-payload.
The changes in the container-engine-for-cc-payload are:
* Removing `/opt/confidential-containers` as part of the uninstall
target.

bundle,config: Update pre/post image

---

tests/e2e/Vagrantfile
tests/e2e/ansible/group_vars/all
tests/e2e/ansible/install_build_deps.yml
tests/e2e/ansible/install_containerd.yml
tests/e2e/ansible/install_docker_ubuntu.yml
tests/e2e/ansible/install_kubeadm.yml
tests/e2e/ansible/install_test_deps.yml
tests/e2e/ansible/main.yml
tests/e2e/ansible/start_docker_registry.yml
tests/e2e/ansible/templates/10-kubeadm.conf.j2
tests/e2e/ansible/templates/kube-flannel.yml.j2
tests/e2e/ansible/templates/kubeadm.conf.j2
tests/e2e/ansible/templates/kubelet.service.j2
tests/e2e/cluster/down.sh
tests/e2e/cluster/up.sh
tests/e2e/lib.sh
tests/e2e/operator.sh
tests/e2e/operator_tests.bats
tests/e2e/run-local.sh
tests/e2e/tests_runner.sh

Adds ansible playbooks to setup the test environment. Kubernetes will be
deployed with kubeadm.
The cluster/up.sh is used to bring up the cluster. Afterwards run
build_install_operator.sh to build and install the operator and
ccruntime. Notice it pushes the operator's controller image to a docker
registry running locally so we avoid pushing/pulling to/from quay.io.
I tested in a Fedora 34 x86_64 machine in a Vagrant VM (see the
Vagrantfile added in this commit). If you wish to run likewise:
$ cd tests/e2e
$ vagrant up tests-e2e-ubuntu2004

ci: bootstrap the test env and install the operator

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime.yaml

Let's update the Kata Containers payload to its latest build, which is
based on the commit f5a65223989b090c91e94faf933ce256fc6e6c9b.
The most significant changes which are part of this new image are:
* TDX support

bundle,config: Update Kata Containers payload

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime.yaml

Thanks to our new CI, we've found that the previous update of the pre-install / post-uninstall image actually introduced a regression in the Operator, as the script would fail trying to remove a non-empty `/opt/confidential-containers` directory.
The main changes in this version of the image are:
* Fixes a bug on uninstall, where we'd try to remove containerd while
its binary was still being used
* Includes more debug messages
* Uses a commit id as the image tag, instead of the time the image was
built, in order to make it easier to link an image to the code.

bundle,config: Update pre-install / post-uninstall image

---

tests/e2e/operator.sh
tests/e2e/operator_tests.bats
tests/e2e/tests_runner.sh

This break the operator tests in two:
- one that will uninstall the operator. On teardown() it no longer attempt to reinstall the operator.
- and one that will try to reinstall the operator. It assumes the first test ran before and passed.
---
ci: change the install/uninstall commands
The commands to uninstall the entire thing (make uninstall && make
undeploy) seems to the sometimes the CI job stuck. We recommend adopters
to use the commands in docs/INSTALL.md, so let's use them on CI as well.

ci: added reinstall operator test

---

tests/e2e/tests_runner.sh

Rather than using the RUNTIMECLASS parameter to modify the contained config, use it to switch between different test files. These tests will then use the appropriate runtime class. The runtime class is a good way to identify different tests because it includes the hypervisor and the hardware that are supported.
This also adds the SEV tests that @ryansavino is working on. See https://github.com/kata-containers/tests/pull/5130
Depends on https://github.com/confidential-containers/operator/pull/80 for  the runtime class.
At some point in the future we might want a more robust way to link test file names to rurntime classes. It's also a bit annoying that we have to specify the names of each of the tests in this repo. That will mean we need extra changes when we push new tests to the tests …

Switch between tests based on runtime class 

---

tests/e2e/ansible/group_vars/all
tests/e2e/ansible/install_test_deps.yml

The bats version on Ubuntu 20.04 don't have all features we need (e.g. setup_file()), so let's build from source. On CentOS it is already built and installed from source, so just enabled it to Ubuntu as well.
Fixes #83

ci: install bats from source

---

config/samples/ccruntime.yaml

Adding runtimeclass for sev. 
Depends on sev kata PRs:
- Packaging for initrd: https://github.com/kata-containers/kata-containers/pull/5120
- Packaging for OVMF: https://github.com/kata-containers/kata-containers/pull/5026
- Packaging for SEV-capable kernel + kernel module https://github.com/kata-containers/kata-containers/pull/5038
- Add agent config to rootfs: https://github.com/kata-containers/kata-containers/pull/5024
- Use depmod in rootfs builder on kernel module(s): https://github.com/kata-containers/kata-containers/pull/5127
- Kata-deploy add kata-qemu-sev shim/runtimeclas https://github.com/kata-containers/kata-containers/pull/5130
Integration testing of all of the SEV components has been successful. Made a cc bundle with all of the PRs added to base CCv0, converted to a docker …

config: add kata-qemu-sev runtimeclass

---

api/v1beta1/ccruntime_types.go
bundle/manifests/cc-operator.clusterserviceversion.yaml
bundle/manifests/confidentialcontainers.org_ccruntimes.yaml
config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
config/manager/kustomization.yaml
deploy/deploy.yaml

Currently, only kata is allowed as runtimeName in the API. The field is copied to CcRuntimeStatus but other than that it's unused.
The first non-kata runtime is nicknamed 'enclave-cc'. Add support for it as a runtimeName identifier.

api: accept enclave-cc runtimeName

---

tests/e2e/Vagrantfile
tests/e2e/tests_runner.sh

Make the non TEE tests generic and configurable, then run them for the kata-qemu and kata-clh runtime classes.
Fixes #90

ci: run non-TEE tests with kata-clh

---

config/manager/manager.yaml
config/samples/ccruntime-ssh-demo.yaml
config/samples/ccruntime.yaml
controllers/ccruntime_controller.go
main.go

CcRuntime is a cluster scoped resource and therefore their instances do not specify any namespace info.
However, the secondary resources are namespaced. Currently, a hard- code value is used but users may want to use some other namespace.
Make the secondary resources namespace configurable using a flag and env var to the operator. By default, use the same (but have it dynamic) namespace as what the operator itself runs in.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

reconcile: use configurable namespace for the secondary resources

---

config/samples/ccruntime-ssh-demo.yaml

SSH demo payload has been released based on the `CC-0.2.0` tag, let's update the image here.

payload: Update the SSH demo payload

---

.github/workflows/gofmt.yaml
.github/workflows/golangci-lint.yaml
controllers/ccruntime_controller.go
controllers/suite_test.go

Let's add two simple actions related to Golang: golangci-lint and gofmt.
Those two actions are proposed to ensure we don't add new code containing neither linter issues nor non properly formatted code.

actions: Add golangci-lint and gofmt GitHub actions

---

.github/workflows/docker-publish.yml
Dockerfile

This is to enable operator image for s390x using buildx. The code changes have been tested to work: 
https://github.com/confidential-containers/operator/actions/runs/3602174182
&rightarrow; an error in the run is attributed to lack of the credential for quay.io/confidential-containers/operator.
Fixes: #131 

actions: Enable operator for s390x

---

Makefile
config/samples/ccruntime-s390x.yaml
install/pre-install-payload/scripts/container-engine-for-cc-deploy.sh
tests/e2e/ansible/group_vars/all
tests/e2e/ansible/install_build_deps.yml
tests/e2e/ansible/install_docker.yml
tests/e2e/ansible/install_kubeadm.yml
tests/e2e/ansible/install_test_deps.yml
tests/e2e/operator.sh
tests/e2e/tests_runner.sh

This is to add e2e tests for s390x based on the same base as x86_64.
A CI job is configured at http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04-s390x-containerd_kata-qemu-PR/ and appears as `cc-operator-e2e-ubuntu-20.04-s390x-containerd_kata-qemu` in the merge status list below. 
Once the PR is merged, the CI job will be triggered for every PR.
Fixes: #138

CI: Add e2e tests for s390x

---

config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml

enclave-cc repo related PR is [here](https://github.com/confidential-containers/enclave-cc/pull/83).
Major ideas:
1. Define ENVs in ccruntime.yaml for configuration.(base64 encoded string)
2. In enclave-cc runtime deployment, deploy script parses ENVs, generates related configuration files and installs to payload specific path.
3. The path has already been mounted to occlum instance when "occlum build".
Signed-off-by: Jie Ren <jie.ren@intel.com>

Add ENVs for enclave-cc specific config parsing in runtime deployment.

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/ccruntime/ssh-demo/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml

Let's point to the payload generated from the 1def978fdf commit, which includes the bump to containerd v1.6.8.1, and has a multi-arch image.

config: Update preInstall payload

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml

ccruntime: Update Kata Containers to the v0.3.0 payload release

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

Let's bump to the latest CI payloads and make sure those are and will continue to be passing the CI till we release the Operator at some point soon.

config: Update to the latest CI payloads

---

tests/e2e/cluster/down.sh

The `kubeadm reset` command currently prints a lot of spam on the console:
> 17:43:55 W0302 16:43:55.496646  774291 cleanupnode.go:93] [reset] Failed to remove containers: [failed to stop running pod I0302: output: I0302 16:43:53.203139  774335 util_unix.go:104] "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat="/run/containerd/containerd.sock" fullURLFormat="unix:///run/containerd/containerd.sock"
This then followed by a lot of followup spam.  I'm not quite sure what is happening, but let's try to get rid of the spam by getting rid of the initial warning.

tests: Specify unix:// prefix on CRI socket path

---

config/release/kustomization.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

As part of v0.4.0 release we're bringing in the following images:
* kata-containers-129e43d1ea5cca528b7b97234b7561219208a244-x86_64
* kata-containers-129e43d1ea5cca528b7b97234b7561219208a244-s390x
* enclave-cc-HW-v0.4.0
* enclave-cc-SIM-v0.4.0

config: Update deps to v0.4.0 release

---

.github/workflows/docker-publish-latest-on-merge.yml

Add `push: true` to the build and push action,
so it actually pushes the container image!
Fixes: #173

workflow: Add push field to action

---

.github/workflows/pre-install-image-publish-on-merge.yml

The container-engine-for-cc-payload will be built only and only if install/pre-install-payload/** files changed, then pushed to quay.io.
Fixes #175

workflow: build and push container-engine-for-cc-payload image on merge

---

tests/e2e/ansible/start_docker_registry.yml

Changing registry to a fixed version so that we will not hit the docker hub rate limit.
Fixes: #182

Fix docker rate limit

---

.github/workflows/e2e.yaml
.github/workflows/enclave-cc-cicd.yaml
bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime/base/ccruntime.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml
docs/PAYLOAD_IMAGE.md
tests/e2e/kind/Dockerfile

---
enclave-cc: Fix preInstall image tag / hostPath / mountPath
We've updated the preInstall image to use Ubuntu 20.04 instead of
CentOS, but we didn't fully reflect the changes for Enclave CC.
---
payloads: Update to an image using ubuntu as base
Both Enclave CC and Kata Containers have switched to using a base image
for their payloads, and we should make sure it works on our side.
As part of the change, we need to update the hostPath / mountPath to
reflect what's needed in order to be able to call `systemctl restart
...` using the new Ubuntu base image.
---

Update payloads to using the ubuntu base image

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml
tests/e2e/tests_runner.sh

I'm updating the Enclave CC and Kata Containers payload.
There's no change on the pre-install payloads since the last bump.

Update payloads to what will become v0.5.0

---

tests/e2e/ansible/start_docker_registry.yml

I ran into that issue while trying to build an environment within CentOS Stream 8, there the requests package is at 2.27.1 version.
---
The distro might have requests < 2.29.0 already so that the package doesn't need to be downgraded. Actually an attempt to downgrade it fail the playbook.
Fixes #206

tests/e2e: downgrade requests package if needed

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

- Now 0.4 release has been tagged, update the config to point to the latest runtime-payloads for 'CI' testing purposes
Fixes: #168

config: Update payloads to the latest CI image

---

config/release/kustomization.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

Update the payloads and the tag for the operator. 
Note the change to the enclave-cc sim payload. Is this correct? @mythi

Bump tags for release v0.6.0

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime/s390x/kustomization.yaml
tests/e2e/tests_runner.sh

This is to add a new runtimeclass `kata-qemu-se` and update its payload image for e2e test.
Fixes: #190

config: Add runtimeclass kata-qemu-se

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime/default/kustomization.yaml
docs/INSTALL.md
tests/e2e/tests_runner.sh

snp: add snp testing

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

Very similar to the last update, but these bundles were built using the tagged version of the subcomponents.
Step 17 of https://github.com/confidential-containers/confidential-containers/issues/111

Update artifacts to release candidates built with tags

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

These are the bundles corresponding to the v0.7.0 tags for CCv0 and enclave-cc. 
Step 23 or https://github.com/confidential-containers/confidential-containers/issues/111

Update artifacts to v0.7.0 release bundles

---

config/release/kustomization.yaml

Step 24 of https://github.com/confidential-containers/confidential-containers/issues/111

release: bump operator version to v0.7.0

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime/base/ccruntime.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml
tests/e2e/tests_runner.sh

This is a change that's been done as part of the CCv0, and it'll simplify a lot the co-existence of the `CCv0` and `main` branch during this time that we're moving things from `CCv0` to `main`.
This pull request is marked as a Draft because it depends on https://github.com/kata-containers/kata-containers/pull/7402 getting merged and having a payload generated from it.

ccruntime: Adapt to the kata payload using `/opt/kata`

---

api/v1beta1/ccruntime_types.go
config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
controllers/ccruntime_controller.go

In this PR we're exposing a few new attributes to the users:
* `Debug`: Whether to enable `debug` for the runtime configuretion, which will also properly configure the CRI Engine accordingly
* `DefaultRuntimeClassName`: The runtime class name that will be used as the default one, and will become the `kata` alias.
Together with these 2 options being exposed, we're leaving the runtime class creation to the runtime payloads, as they know better than the Operator what are the possible podOverhead and, in the future, NFD rules to be used.
Right now this is a draft as it depends on content that's not yet part of the Kata Containers payload, and also work that's been ongoing on the Enclave CC side (thanks @mythi for that!).  Regardless, I'd love to hear feedback from the other operator …

CRD: Expose more options to the users and let the payload take care of the runtime class creation

---

.github/workflows/e2e.yaml
controllers/ccruntime_controller.go
tests/e2e/enclave-cc-kind-config.yaml

the e2e test is currently testing the operator from quay.io instead of the one built+pushed to the local registry. Fix this.
@fidencio @mythi

Fix e2e test

---

config/samples/ccruntime/base/ccruntime.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
controllers/ccruntime_controller.go
install/pre-install-payload/containerd/Dockerfile
install/pre-install-payload/scripts/container-engine-for-cc-deploy.sh

This adapts the operator to changes that happened in kata-deploy in kata-containers/kata-containers#7520, which switched to using nsenter to interact with systemd.

Use host systemctl

---

.github/workflows/e2e.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/base/kustomizeconfig.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml
install/pre-install-payload/containerd/payload.sh
install/pre-install-payload/scripts/container-engine-for-cc-deploy.sh
tests/e2e/ansible/group_vars/all
tests/e2e/ansible/install_build_deps.yml
tests/e2e/ansible/install_test_deps.yml
tests/e2e/operator.sh

Currently changes on install/pre-install-payload directory aren't tested because the scripts aren't re-building the pre-install-payload image, and with this change the image will always be built and used.
Fixes #177

tests/e2e: test changes to the pre-install-payload image

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/ssh-demo/kustomization.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

The tags for the quay.io/confidential-containers/reqs-payload image were not set to the latest tag and were set to the tag of an image that went into a crash loop when you ran it as part of the operator installation.
Fixes: #254

pre-install-payload: Use latest tagged runtime-payload image

---

config/samples/ccruntime/base/ccruntime.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
install/pre-install-payload/Dockerfile
install/pre-install-payload/Makefile
install/pre-install-payload/payload.sh
install/pre-install-payload/scripts/reqs-deploy.sh

This work is required as we'll move out from the forked version of containerd, but not for all the projects, and not without requiring a minimum version of containerd to do so.
As enclave-cc will still be depending on the containerd fork for v0.8.0, and as we may need to still install the minimum version of containerd on clusters using, for a reason or another, containerd v1.6.x, we need to handle those two different installations in a graceful manner.

pre-install-payload: Handle official and VFIO / GPU containerd installations

---

config/samples/enclave-cc/hw/kustomization.yaml

The 'images' key was missing and resulted in
error: invalid Kustomization: yaml: line 8: did not find expected key

enclave-cc: fix HW kustomization

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This covers steps 4 and 5 from the release checklist [here](https://github.com/confidential-containers/confidential-containers/issues/145)

config: set operator payloads for v0.8.0 release

---

install/pre-install-payload/Dockerfile
install/pre-install-payload/scripts/reqs-deploy.sh

We've been leaving the nydus-snapshotter config behind because we were
trying to remove it from a path that was changed from the first
iteration of the nydus-snapshotter addition, but ended up not being
noticed during review.
While here, let's also make sure to entirely remove
`/opt/confidential-containers/share`, as nydus-snapshotter is the only
bit of code using that.
Fixes: #278
While here let's also pre-remove ctr cleanup of nydus snapshotters
This has proven to be useless as it is, as `ctr` doesn't have access to
the `/var/run/{containerd,containerd-nydus}` to actually be able to
perform any operation.
We could, obviously, expose those to the operator, but I'm very much
against adding even more host mounts to the operator, unless this is
strictly needed, and right now I don't think …

pre-install: pre-install: Remove nydus-snapshotter config

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml
tests/e2e/operator.sh

This covers step 13 from the release checklist [here](https://github.com/confidential-containers/confidential-containers/issues/145)

config: update operator payloads for v0.8.0 release

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This covers step 19 from the release checklist [here](https://github.com/confidential-containers/confidential-containers/issues/145)

config: update operator to use release tags for enclave-cc and kata

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This was waiting on the merge from [PR 284](https://github.com/confidential-containers/operator/pull/284), which is now done. This grabs the corresponding reqs-payload hash and sets the operator to point to that bundle.

config: set reqs-payload for v0.8.0 release

---

tests/e2e/operator.sh
tests/e2e/operator_tests.bats
tests/e2e/tests_runner.sh

Remove the kata-containers `CCv0` e2e tests in the operator as these tests are on a dead branch of a dead repo We also have had issues with them not being suitable as they programmatically change the configuration, which isn't likely to work in GHA, but isn't what we want to test either.
Later we should add an e2e smoke test that ensures that the kata-payload integrated with things like nydus-snapshotter than the operator is responsible for setting up and configuring as discussed in https://github.com/confidential-containers/operator/issues/239

tests/e2e: Remove kata-containers test

---

bundle/manifests/cc-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/cc-operator.clusterserviceversion.yaml
config/samples/ccruntime/base/ccruntime.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml
docs/INSTALL.md
tests/e2e/tests_runner.sh

- Switch the `CCv0` payload to the kata-deploy main version
- Note: I've not replaced the enclave-cc payloads as they are created in a different way IIUC
- Update operator and reqs-payload images to use latest tags

Kata main payload

---

.github/workflows/ccruntime_e2e.yaml
tests/e2e/cluster/up.sh
tests/e2e/lib.sh
tests/e2e/operator.sh

use the azure runners provided by "confidential-containers/infra" to run the kata-clh and kata-qemu workflows.

WiP e2e: Move tests to gh action using azure workers

---

docs/DEVELOPMENT.md

Created a new "Continuous Integration (CI)" section in the developer's guide to explain the e2e CI jobs types, how/who can execute them as well as how to run some of them locally.
Fixes #113

docs/DEVELOPMENT: document the CI

---

.github/workflows/makefile.yml

So we check the bundle is not broken way before we try to publish it on the Operator Hub.

actions: build the bundle on pull requests

---

controllers/ccruntime_controller.go

Let's start properly setting a specific snapshotter per runtime handler configured for containerd.
This work depends on a work done on the Kata Containers side to better support setting snapshotters per runtime handler.
The PR from the Kata Containers side is:
https://github.com/kata-containers/kata-containers/pull/8655.

controller: Handle snapshotter per handler

---

.github/workflows/ccruntime_e2e.yaml

---
gha: ccruntime_e2e: Avoid fail-fast
Every now and then we'll face errors that may be different depending on
the distro being used, due to some distro changes or even some flakiness
in the tests.
Till everything is 100% stable, which is not the case yet, we better
allow the tests to finish even if one test fails, giving us a better
idea of the problem being a generic one or specific to flakiness / one
distro.
---
gha: ccruntime_e2e: Add a 30 minutes timeout
Today I've faced one test hanging for more than one hour, stuck, without
giving us any useful information, leaving the "cancel" option (which is
up to the user to do) as the only option to finish the test and re-start
it.
As a possible way to avoid wasting resources for too long, let's simply
add a timeout of 30 minutes in the …

gha: ccruntime_e2e: Do **NOT** fail fast and add a timeout for the test execution

---

config/samples/ccruntime/s390x/kustomization.yaml

Due to the fact that kustomize does not allow the 2nd level of resource patch, this commit is to make the resources overridden by base directly.
Fixes: #320

kata-payload: Make resources for s390x overridden by base

---

.github/workflows/ccruntime-nightly.yaml
.github/workflows/ccruntime-pr.yaml
.github/workflows/ccruntime_e2e.yaml
tests/e2e/ansible/install_docker.yml
tests/git-helper.sh

This PR is to migrate the following e2e tests for s390x in Jenkins to GHA:
- confidential-containers-operator-main-ubuntu-20.04-s390x-containerd_kata-qemu-baseline
- confidential-containers-operator-main-ubuntu-20.04-s390x-containerd_kata-qemu-PR
- confidential-containers-operator-main-ubuntu-20.04-s390x-SE-daily
It will be staying in a `work-in-progress` state and the workflow structure will be changed based on that of `x86_64`. (i.e. a decision could be made when https://github.com/confidential-containers/operator/pull/260 is finalised.)
The workflow itself has been tested several times
- https://github.com/BbolroC/cc-operator/actions/runs/7017907526
- https://github.com/BbolroC/cc-operator/actions/runs/7017396678
- https://github.com/BbolroC/cc-operator/actions/runs/7011926398
The …

tests/e2e: Migrate e2e test for s390x to GHA

---

docs/INSTALL.md

This PR updates the install instruction documentation to have RELEASE_VERSION as a variable to have consistency across the document and avoid installation failures when it is not defined as a variable.

doc: Update install instructions documentation

---

docs/DEVELOPMENT.md

The DEVELOPMENT.md does not cover a case where a user wants to build/test a custom operator/payload image. This is to supplement the case. This also covers an update on the incorrect information for s390x e2e test.
This PR should be merged after an e2e test for s390x in #295 runs properly.

doc: Include custom build for DEVELOPMENT.md

---

docs/INSTALL.md

Just a small fix/clarification.
Not all resources are in a namespace. Some resources like CRDs, ClusterRoles and ClusterRoleBinding are non-namespaced resources. Lets make this clear.

docs: small clarification about non-namespaced resources

---

docs/INSTALL.md
docs/how-to/INSTALL-CC-WITH-IBM-SE.md

Due to the limitation that a public key used to encrypt a secure image is associated with a machine specific private key, a user cannot install and run a confidential container with IBM Secure Execution from release.
This is to provide a guide for how to achieve the goals above with a custom build.

doc: provide a guide for how to install CC with IBM Secure Execution

---

tests/git-helper.sh

`[ ! command -v jq &> /dev/null ]` doesn't work for checking the existing of yq because if enclosed in `[]` it won't check the return code of `command`.
---
Found this problem when running the CI jobs for PR #338.
I don't know why  on previous execution jq existed on the system so that we didn't catch the issue before.

tests/git-helper.sh: fix yq checking

---

tests/e2e/operator.sh

This PR introduces general fixes to the test/e2e operator script, like fixing the indentation, using a variable that has been already declared and use in the script.

tests/e2e: General fixes to the operator script

---

.github/workflows/ccruntime_e2e.yaml
tests/e2e/operator.sh
tests/e2e/operator_tests.bats
tests/e2e/run-local.sh

There are several improvements to the e2e pipeline to avoid odd returns as well as to interrupt on hangs. Last but not least I added extra messages that should improve reading the logs.
I'm definitely open to suggestions to remove/improve individual commits....

CI: Improve e2e tests reliability

---

.github/workflows/docker-publish-latest-on-merge.yml
.github/workflows/docker-publish-on-tag.yml
.github/workflows/makefile.yml
.github/workflows/pre-install-image-publish-on-merge.yml

We should at least be consistent with the ubuntu base images we're running in the workflows. I also opt to use ubuntu-22.04 and not ubuntu-latest.
Other repos in the org can take a similar change if reviewers want.

CI: Use ubuntu-22.04 and not ubuntu-latest in workflows

---

tests/e2e/ansible/group_vars/all
tests/e2e/ansible/install_docker.yaml
tests/e2e/ansible/install_kubeadm.yaml

Fedora also can be used to run k8s clusters locally. Add the fedora requirements to allow for testing.

tests/ansible: Add fedora  linux distros

---

tests/e2e/ansible/install_build_deps.yaml
tests/e2e/ansible/install_containerd.yaml
tests/e2e/ansible/install_docker.yaml
tests/e2e/ansible/install_kubeadm.yaml
tests/e2e/ansible/install_test_deps.yaml
tests/e2e/ansible/start_docker_registry.yaml

Let's allow to re-try tasks that make sense and a few cleanups.

ci: Improve reliability of ansible tasks

---

tests/e2e/lib.sh
tests/e2e/operator.sh
tests/e2e/run-local.sh

To have a better consistency across the test/e2e scripts this PR improves the variable definition by using local as a best practice.

tests: Improve variable definition in tests/e2e scripts

---

.github/workflows/makefile.yaml
go.mod
tests/e2e/ansible/group_vars/all

Please check out the issue below for details.
It is to update a go version to 1.21.7 which makes the CI go green again.
Fixes: #356

CI: bump go version to 1.21.7

---

install/pre-install-payload/payload.sh
install/pre-install-payload/scripts/reqs-deploy.sh

This PR adds general fixes in the pre-install scripts like removing tab spaces where they are not needed as well as improving the definition of the variables.

pre-install: General fixes in pre-install scripts

---

.github/workflows/pre-install-image-publish-on-merge.yaml
install/pre-install-payload/payload.sh

This is attempting to fix the failing GHA action [here](https://github.com/confidential-containers/operator/actions/workflows/pre-install-image-publish-on-merge.yaml) so that the v0.9.0 release can continue.
`docker manifest create` example is [here](https://docs.docker.com/reference/cli/docker/manifest/):
```
docker manifest create 45.55.81.106:5000/coolapp:v1 \
45.55.81.106:5000/coolapp-ppc64le-linux:v1 \
45.55.81.106:5000/coolapp-arm-linux:v1 \
45.55.81.106:5000/coolapp-amd64-linux:v1 \
45.55.81.106:5000/coolapp-amd64-windows:v1
```

Release: update docker manifest create commands

---

install/pre-install-payload/payload.sh

This effectively reverts PR 366 and drops the guarding quotes that were added around `extra_docker_manifest_flags` in 351.

Release: attempt to fix docker manifest commands

---

Makefile

to provide a standard way to clean the environment after build.
Note I'm not a heavy "go" user so I simply took the paths from ".gitignore". I experimented with "go clean" but it did not work for me.

Add "make clean" target

---

.github/workflows/enclave-cc-e2e.yaml
config/release/kustomization.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

The payloads for v0.9.0-alpha
@stevenhorsman or @BbolroC can you guys confirm that we do not need the s390x suffix for the s390x CRD?

Update payloads for v0.9.0-alpha0

---

.github/workflows/enclave-cc-cicd.yaml
.github/workflows/enclave-cc-e2e.yaml
tests/e2e/enclave-cc-pod-sim.yaml

Now that both e2e (for PRs) and cicd (nightly) tests are using the updated payloads with the new Occlum instance path, we can drop the sed lines and update the test deployment use the new path directly.

ci: update enclave-cc tests

---

install/pre-install-payload/payload.sh

supported_arches variable is defined but not used during manifest create step. With this patch we can easly disable arches for quick development test.

payload: reuse supported_arches

---

tests/e2e/ansible/install_containerd.yaml
tests/e2e/ansible/install_test_deps.yaml

Ansible used to have a "feature" where it would warn you if you wrote a shell command that could be implemented with a module instead. The shell option had an option to disable these warnings.
These features were deprecated in ansible 2.11 and removed in anbsible 2.14. This PR removes the warn option. Otherwise the playbooks won't work. 
This does mean that people using an older version of ansible might see the warnings.

tests: remove deprecated ansible option

---

docs/DEVELOPMENT.md
tests/e2e/Vagrantfile

inspired by me trying to follow the documentation to set things up

Docs: Improve the steps to run e2e locally

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

- After we updated to pick up nydus-snapshotter v0.3.13 in the pre-reqs image, start picking up this version.

pre-reqs: Bump reqs-payload image

---

config/samples/ccruntime/peer-pods/kustomization.yaml

- We have a bunch of outstanding issues with the peerpodsconfig change that moved the management of the cloud-api-adaptor daemonset and peer-pods configmap to be owned by the operator rather than cloud-api-adaptor. In order to try and switch away from the outdated 0.8 operator and consume the main kata payload we decided to switch back to the cloud-api-adaptor managing it's daemonset and config, until we can find a testable and strategic path for the operator management, so we'll comment out the kustomize that runs peerpodsconfig-ctrl until we have that solution

peer-pods: Comment out peerpodsconfig.yaml

---

config/samples/ccruntime/base/ccruntime.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

The release is done, so let's go back to the upstream bundles for enclave-cc, kata, and reqs-deploy

Go back to latest payloads after release

---

tests/e2e/ansible/start_docker_registry.yaml

The issue https://github.com/docker/docker-py/issues/3113 seems to be resolved. The pinned version of requests (2.28.1) is no longer compatible with the current docker pip, resulting in errors like:
```
"Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"
```
Initially, we attempted to allow pip to install requests according to its dependency tree.
However, the issue persists on Ubuntu 22.04, and it appears to be related to https://github.com/docker/docker-py/issues/3256.
The best solution so far is to pin the version of the package to less than 2.32.
The change is verified at https://github.com/confidential-containers/operator/actions/runs/9204691086?pr=382
Fixes: #381 

CI: Pin requests' version less than 2.32

---

.github/workflows/ccruntime_e2e.yaml
docs/DEVELOPMENT.md

Please, see each commit message for more details.
Although we don't have a TDX machine plugged yet, it'd be good to have this reviewed as the tests won't be able to run before they're merged, as it's relying the `pull_request_target` event.
Once the TDX machine is ready, I'd be fine on having this one merged (after review, of course).

ci: Run the e2e tests on TDX

---

Makefile
install/pre-install-payload/payload.sh
tests/e2e/run-local.sh

This PR adds build args for proxy when using docker build, this is specially needed when we are behind a proxy to avoid failures.

Makefile: scripts: Add build args for proxy when using docker build

---

config/release/kustomization.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This updates the payloads for v0.9.0-alpha1

Release: Update payloads for v0.9.0-alpha1

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This reverts the changes to operator that were done for the release here:
https://github.com/confidential-containers/operator/pull/388
Note: 1 of the commits there, namely changing the operator tag, should not be reverted https://github.com/confidential-containers/operator/pull/388/commits/004361a1496c90efdbba9abc52b91d9ed2c2f19b

Release: Revert v0.9.0-alpha1 release-specific changes back to dev values

---

config/crd/bases/confidentialcontainers.org_ccruntimes.yaml

PR https://github.com/confidential-containers/operator/pull/376 introduced support for pull_type option, however the manifest update was missed. This fixes it.

crd: Fix manifest due to changes in the ccRuntime CRD

---

.github/workflows/ccruntime_e2e.yaml
docs/DEVELOPMENT.md

Enables testing of :
1. kata-qemu-sev runtime class on SEV and
2. kata-qemu-snp runtime class on the SNP 
self hosted runners respectively.
Updated documentation to reflect the same.

ci: Enable running the ccruntime_e2e tests on AMD SEV/SNP nodes

---

.github/workflows/ccruntime_e2e.yaml

- The instance need to be a label on the GHA runner, not the runner name, so fix this

ci: Fix up amd runner labels

---

tests/e2e/operator.sh

This PR gives general improvements to the operator script that is being used in tests. This PR includes changes like better variable definition and the use of a variable that has been already defined.

tests: General improvements to operator script

---

.github/workflows/ccruntime_e2e.yaml
tests/e2e/ansible/install_test_deps.yaml

This PR authenticates for github to increase the threshold for rate limiting while installing kustomize and avoid the random failures that are impacting several CIs.

tests.e2e.ansible: Fix to increase github rate limiting for kustomize

---

.github/workflows/ccruntime_e2e.yaml

The following hooks:
- ACTIONS_RUNNER_HOOK_JOB_STARTED
- ACTIONS_RUNNER_HOOK_JOB_COMPLETED
could perfectly replace the existing {pre,post}-action scripts and will make a workflow independent of the runner context. This PR wipes out all GHA steps where the actions are triggered.
@AdithyaKrishnan please let me know when the runner for SEV/SNP is ready for this. I will ask for review when you guys are ready. Thanks.

GHA: Remove {pre,post}-action steps for self-hosted runners

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #397 .

Release: Revert v0.9.0 release-specfic changes back to dev values

---

config/samples/ccruntime/default/kustomization.yaml

Depending on the environment where we deploy Confidential Containers, setting up the proxy is required for the agent to be able to connect with the external world.
With that in mind, mainly considering this is needed for the basic TDX CI, let's ensure we expose to the users a way to set it up.

crd: Expose agent{Https,No}Proxy

---

docs/PEERPODS-TEST.md

This PR fixes a misspelling on the peer pods test document.

docs: Fix misspelling on peer pods test document

---

tests/e2e/ansible/install_test_deps.yaml

This PR installs the kustomize CLI from source in order to avoid the random failures due to the Github Actions rate limitations.

tests:e2e: Install kustomize from the Go source code

---

Makefile

A version of controller-gen is quite old and fails to run with the latest go:
```
panic: runtime error: invalid memory address or nil pointer dereference
```
This PR updates the package to the latest version.

tools: Bump controller-gen to v0.15.0

---

.github/workflows/ccruntime-nightly.yaml
.github/workflows/ccruntime_e2e.yaml

Recently, an additional s390x runner was added to the organization. However, it is insufficient for running the operator e2e tests and will function as a supplementary builder.
This commit changes the label for the platform from s390x to s390x-large to differentiate the existing runner.

GHA: Change label from s390x to s390x-large

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml

the CI is currently blocked due to recent change in kata-containers as described here:
https://github.com/confidential-containers/operator/issues/391
let's restore the testing with latest-known-to-work kata-containers to allow the CI to run

CI: Freeze kata-containers repo to workaround deploy bug

---

Makefile
bundle/manifests/cc-operator.clusterserviceversion.yaml
bundle/manifests/confidentialcontainers.org_ccruntimes.yaml
config/manager/kustomization.yaml
config/manifests/bases/cc-operator.clusterserviceversion.yaml
docs/OPERATOR_HUB.md

I submitted the https://github.com/k8s-operatorhub/community-operators/pull/4787 to publish 0.9.0 bundle in operator hub and coco's operator landing page in hub is already updated (see https://operatorhub.io/operator/cc-operator)
Here I'm sending the changes I did to publish it as well as a few fixes to docs.

release: changes to publish 0.9.0 in operator hub

---

tests/e2e/run-local.sh

with bash debug output we can easily tell what part of CI hanged or failed.
@wainersm this should even further improve the https://github.com/confidential-containers/operator/pull/412 and allow to debug failures in CI, what do you think?

tests: Enable bash debug in "run-local.sh"

---

tests/e2e/operator.sh

Sometimes the operator hangs on uninstall and we don't know exactly where it is halted. This added some echos to help on debugging.

tests: add debug msgs to uninstall_ccruntime

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml

This reverts commit daec53827aca650613f06a53e85c25b54d4a3a92, as the issue with kata-deploy has been fixed.

Revert "CI: Freeze kata-containers repo to workaround deploy bug"

---

.github/workflows/ccruntime_e2e.yaml

the free-runners come with pre-installed containerd which sometimes collides with the one we install. We also need to move docker images to /mnt due to limitted root (/) partition.
Note I tried testing this on my fork https://github.com/ldoktor/coco-operator/pull/4 but for some reason I can only use `ubuntu-latest` while `ubuntu-2204` (which is the same as `ubuntu-latest`) fails, which is why I left the `az-*` runners on for now, we can remove them once the GH runners stabilize.

ci: Start using the free GH runners for e2e testing

---

.github/workflows/ccruntime_e2e.yaml

the reason GH is not picking up the jobs is a missing "." in the label name.

ci: Fix the GH free-runners label

---

.github/workflows/ccruntime_e2e.yaml
docs/DEVELOPMENT.md

The first commit fixes the workflow after the instance name changed to contain `.` in the version. The second commit adds the new jobs to the CI documentation.

ci: GH runners fixes

---

.github/dependabot.yml
.github/workflows/lib-codeql.yaml
.github/workflows/makefile.yaml

This PR is a reference for few improvements in our repositories
1. enable dependabot github-actions updates using pinned versions (dependabot understands pinned versions nowadays). Pinned versions are considered safe since attackers could re-push tags. The move to pinned versions must be done manually.
2. enable CodeQL checks for our Go based code (to be checked: maintainers might have to enable this in the repo settings also)
Ref: https://github.com/confidential-containers/confidential-containers/issues/46

enable CodeQL checks

---

install/pre-install-payload/scripts/reqs-deploy.sh

the cri-o runtime uses "crio.service" service name (tested on OCP 4.14)
Related to: #418

pre-install: Fix service name for cri-o runtime

---

.github/workflows/ccruntime_e2e.yaml

the github free-runners seem to perform well and stable, let's disable the azure runners.

ci: Remove azure-based workers pipelines

---

.github/workflows/ccruntime-pr.yaml

the "e2e-pr / operator tests" is always required so we have to run it even though it does not make much sense.
This should help with https://github.com/confidential-containers/operator/pull/444

ci: Always run e2e testing

---

Makefile
bundle.Dockerfile
bundle/manifests/cc-operator.clusterserviceversion.yaml
bundle/manifests/confidentialcontainers.org_ccruntimes.yaml
bundle/metadata/annotations.yaml
config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
config/manager/kustomization.yaml
config/manifests/bases/cc-operator.clusterserviceversion.yaml
config/rbac/role.yaml

I submitted the https://github.com/k8s-operatorhub/community-operators/pull/5081 to publish 0.10.0 bundle in operator hub. After it is merged, coco's operator landing page in hub should get updated (see https://operatorhub.io/operator/cc-operator).
Here I'm sending the changes I did to publish it.

release: changes to publish 0.10.0 in operator hub

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #448

Release: Revert v0.10.0 release-specfic changes back to dev values 

---

.github/workflows/ccruntime_e2e.yaml

The CI machines for TDX are being brought down for some time. Disable tdx related jobs till they are brought back up to avoid jobs being queued.

ci: Remove tdx CI jobs temporarily

---

docs/DEVELOPMENT.md

This PR removes the GH runners of the e2e jobs that are not longer being supported on the current CI.

docs: Remove GH runners e2e not longer supported

---

.github/dependabot.yml
.github/workflows/ccruntime_e2e.yaml
.github/workflows/docker-publish-latest-on-merge.yaml
.github/workflows/docker-publish-on-tag.yaml
.github/workflows/enclave-cc-cicd.yaml
.github/workflows/enclave-cc-e2e.yaml
.github/workflows/gofmt.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/lib-codeql.yaml
.github/workflows/makefile.yaml
.github/workflows/pre-install-image-publish-on-merge.yaml

manual upgrades from #431 and #432.
potentially interesting read https://pin-gh-actions.kammel.dev/
Rationale:
Not because of being paranoid but mainly because it's considered a good security practice. That practice is also checked by tools like OpenSSF Scorecard so if our repos are benchmarked using that common tooling, it shows we are "compliant".

gh action updates

---

.github/workflows/ccruntime_e2e.yaml

This reverts commit a1a68e01c15d7b010fc0b3b610eef33452f584d6, as the TDX machine is back online.

Revert "ci: Remove tdx CI jobs temporarily"

---

controllers/ccruntime_controller.go
controllers/common.go

This PR implements support for ImagePullPolicy which is present in the CRD but not actually used (default Always).

fix: add support for imagePullPolicy for installer daemonsets (#395)

---

install/pre-install-payload/payload.sh

This PR removes the containerd dir variable in the payload script as it is not being used.

payload: Remove unused variable in payload script

---

Dockerfile.peerpods

While building this Dockerfile we got the following warning 'FromAsCasing: as and FROM keywords casing do not match', this PR fixes it.

Fix warning in Dockerfile.peerpods

---

controllers/ccruntime_controller.go

We are currently experiencing issues with finalizers hanging when deleting ccruntime. Initial debugging has pinpointed the problem to the processCcRuntimeDeleteRequest method.
This method is large and has a cyclomatic complexity of 21. I'm taking this opportunity to use early returns to reduce nesting and simplify control flow. Additionally, this is moving the finalizer handling logic to its own method.
This refactor should not change the current logic, only improve readability and maintainability.
Related to #391.

ccruntime: processCcRuntimeDeleteRequest split

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #465 .

Release: Revert v0.11.0 release-specfic changes back to dev values

---

.github/workflows/docker-publish-latest-on-merge.yaml
.github/workflows/docker-publish-on-tag.yaml
install/pre-install-payload/payload.sh
tests/e2e/ansible/group_vars/all

Added arm64 images build for operator and it's pre-reqs payload

actions: enable arm64 images for operator

---

docs/DEVELOPMENT.md

The added machine table links the machine's assigned labels to the jobs required labels.
Corrected some mistakes and label assignments.
Formatting.
Fixes: #316
Signed-Off-By: Ryan Savino <ryan.savino@amd.com>

CI Documentation - added machine list table and label columns

---

tests/e2e/operator.sh

The existing condition in the `start_local_registry` function does not work as expected:
```
while ! curl -s localhost:5000 -o $cnt -lt 5; do
```
This could result in an infinite loop because the curl return value is not correctly combined with the counter condition. Instead of exiting after 5 retries, the loop increments $cnt indefinitely as long as curl fails, as shown:
```
+ cnt=5
+ curl -s localhost:5000 -o 5 -lt 5
+ sleep 1
+ cnt=6
+ curl -s localhost:5000 -o 6 -lt 5
+ sleep 1
+ cnt=7
+ curl -s localhost:5000 -o 7 -lt 5
+ sleep 1
```
Additionally, `-o $cnt -lt 5` can be misinterpreted as an argument for curl, further compounding the issue.
This PR resolves the misbehavior by:
1.  Properly combining conditions with &&
2.  Incrementing $cnt in a modern bash style
The corrected logic is …

ci: Fix unintended loop behavior when checking docker registry health

---

tests/e2e/operator_tests.bats

the operator reinstall test only installs the runtime and finishes. This can cause issues in consequent tests or in cleanup as was observed in the CI (hang in cleanup after quick deployment).

tests: Wait for stabilization after deployment

---

hack/release-helper.sh

During the CoCo release process, there are a couple of tedious steps in the operator repo that can be automated. The script in this PR attempts to do that.
We just used this to help with the v0.10.0 release. The checklist is [here](https://github.com/confidential-containers/confidential-containers/issues/242). This script helps with steps 4 and 5.
This script has been used for v0.9.0 and now v0.10.0, so it's been run a couple of rounds and been found useful enough to submit for review.

Release: new helper script to improve the release process

---

.github/workflows/ccruntime_e2e.yaml
install/pre-install-payload/payload.sh

Currently the pre-install-payload builds always all supported payload archs. Let's allow tweaking this by "pre_install_payload_archs" environment variable and use that in our e2e pipelines to only build the current architecture.
Related to: https://github.com/confidential-containers/operator/pull/474#pullrequestreview-2506389242

actions: Build only current arch in e2e testing

---

.github/workflows/ccruntime_e2e.yaml
controllers/ccruntime_controller.go
controllers/common.go
install/pre-install-payload/scripts/reqs-deploy.sh
tests/e2e/operator.sh

This is a 2nd stage of https://github.com/confidential-containers/operator/pull/482 which adds a new node label to be used as nodeSelector for daemon uninstall and removes the hardcoded 60s sleep. On top it also re-names the labels which might be invasive right now but should be aligned to how kata uses labels. Take this as a suggestion open to negotiation :-)

Several changes to cc operator labels

---

Makefile
bundle/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/cc-operator.clusterserviceversion.yaml
bundle/manifests/confidentialcontainers.org_ccruntimes.yaml
config/crd/bases/confidentialcontainers.org_ccruntimes.yaml
config/manager/kustomization.yaml
config/manifests/bases/cc-operator.clusterserviceversion.yaml

I submitted the https://github.com/k8s-operatorhub/community-operators/pull/5611 to publish 0.10.2 bundle in operator hub and these are the changes on our side for the publish.

bundle: updates for 0.12.0

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

release: Post-release reverts
This reverts the hard-coding of payload versions
for the 0.12 release done in #487

release: Post 0.12.0 release reverts

---

.github/workflows/ccruntime_e2e.yaml
.github/workflows/makefile.yaml

This changes enables e2e and makefile test on arm64 runner. There are some prerequisite.
Ther operator's CI is as following: (${\color{red}red}$ parts are added by this change)
* ccruntime-nightly (executed at 02:00 everyday)
* call ccruntime-e2e (e2e test on amd64, s390x, ${\color{red}arm64}$)
* ccruntime-pr (exectued at pull request)
* call ccruntime-e2e (e2e test on amd64, s390x, ${\color{red}arm64}$)
* docker-publish-latest-on-merge (build images on amd64)
* docker-publish-on-tag (build images on amd64)
* enclave-cc-cicd (sgx specific test on amd64)
* enclave-cc-e2e (sgx specific test on amd64)
* gofmt (lint on amd64)
* golangci-lint (lint on amd64)
* makefile
* build test on amd64, ${\color{red}arm64}$
* lib-codeql (static analysis on amd64)
* envtest on amd64, ${\color{red}arm64}$

ci: Enable ccruntime-e2e and makefile test on arm64

---

tests/e2e/ansible/install_docker.yaml

When upgrading the s390x runner to Ubuntu 24.04, the following error occurred:
```
Destination directory /usr/etc/systemd/system does not exist
```
Previously, the script replaced `/lib` with `/etc` in systemd paths. However, on Ubuntu 24.04, `systemctl show -p FragmentPath docker.service` returns `/usr/lib/systemd/system/docker.service`, rendering the old substitution invalid.
This PR updates the destination directory to
`/etc/systemd/system/docker.service` and fulfills the copy logic if the fragment path starts with either `/lib` or `/usr/lib`.

tests/e2e: Fix systemd path handling for Ubuntu 24.04 on s390x

---

.github/dependabot.yml

this should group all dependabot PRs, which should decrease the amount of CI and acks for GH action version changes.

dependabot: Group dependabot PRs

---

tests/e2e/run-local.sh

we are using "timeout" to limit cleanup time in CI, but the default -15 won't interrupt on some occasions. Let's use -9 instead to not to block in case the cleanup fails.
Note this is only about the cleanup part of the e2e run-local.sh, every hang inside the testing itself should still result in a failure.

tests: Send -9 on cleanup interruption

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

This reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #513 .

Release: Revert v0.13.0 release-specfic changes back to dev values

---

.github/workflows/ccruntime_e2e.yaml

the ubuntu 20.04 is deprecated and removed from GH runners, let's replace it with the latest 24.04 to ensure various versions keep working well.

ci: Replace deprecated GH ubuntu 20.04 for 24.04

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

It reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #525 .

Release: Revert v0.14.0 release-specfic changes back to dev values

---

.github/workflows/ccruntime_e2e.yaml
docs/DEVELOPMENT.md

kata-deploy supports Ubuntu 24.04 (and 25.04) based TDX enablement. Since the operator e2e does not test any TEE specifics, it's enough to test that kata-qemu-tdx runtimeclass gets created on a vanilla Ubuntu 24.04.

e2e: run tdx operator tests on ubuntu-24.04 runner

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

Revert the 0.15 release hard-coded payloads in #533, so we can test the latest kata payloads given we are half-way through the release cycle and there are some breaking changes in Kata

Post 0.15.0 release reverts

---

.github/workflows/ccruntime_e2e.yaml
config/release/kustomization.yaml
config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

PR for step#5 of [checklist for v0.16.0](https://github.com/confidential-containers/confidential-containers/pull/318)

Release: Update payloads for v0.16.0

---

config/samples/ccruntime/default/kustomization.yaml
config/samples/ccruntime/peer-pods/kustomization.yaml
config/samples/ccruntime/s390x/kustomization.yaml
config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
config/samples/enclave-cc/hw/kustomization.yaml
config/samples/enclave-cc/sim/kustomization.yaml

It reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) of the PR https://github.com/confidential-containers/operator/pull/539 .

Release: Revert v0.16.0 release-specfic changes back to dev values
